# Generated by Django 5.1.1 on 2024-09-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_useraccount_name_alter_useraccount_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
