# Generated by Django 5.1.1 on 2024-09-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_useraccount_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
