# Generated by Django 5.1.1 on 2024-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_useraccount_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("pantone_value", models.CharField(max_length=20)),
            ],
        ),
    ]
