# Generated by Django 5.1.1 on 2024-09-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_useraccount_first_name_and_more"),
        ("authentication", "0006_resource"),
    ]

    operations = []
