# Generated by Django 5.1.1 on 2024-09-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_delete_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/no-avatar.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
