# Generated by Django 5.1.1 on 2024-09-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_resource_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="user",
            new_name="user_id",
        ),
    ]
