# Generated by Django 5.1.1 on 2024-09-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_rename_user_resource_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
